# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 122
  rpc: https://rpc.fuse.io
  start_block: 27175571
  contracts:
  - name: VoltageV3Factory
    address:
    - 0xaD079548b3501C5F218c638A02aB18187F62b207
    handler: src/EventHandlers.ts
    events:
    - event: FeeAmountEnabled(uint24 indexed fee, int24 indexed tickSpacing)
    - event: FeeAmountExtraInfoUpdated(uint24 indexed fee, bool whitelistRequested, bool enabled)
    - event: OwnerChanged(address indexed oldOwner, address indexed newOwner)
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
    - event: SetLmPoolDeployer(address indexed lmPoolDeployer)
    - event: WhiteListAdded(address indexed user, bool verified)
  - name: VoltageV3Pair
    # address:
    # - 0x06b6949Fca3706c25A312c1104B7e4fa11ce0BB6
    handler: src/EventHandlers.ts
    events:
    - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
    - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
    - event: CollectProtocol(address indexed sender, address indexed recipient, uint128 amount0, uint128 amount1)
    - event: Flash(address indexed sender, address indexed recipient, uint256 amount0, uint256 amount1, uint256 paid0, uint256 paid1)
    - event: IncreaseObservationCardinalityNext(uint16 observationCardinalityNextOld, uint16 observationCardinalityNextNew)
    - event: Initialize(uint160 sqrtPriceX96, int24 tick)
    - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
    - event: SetFeeProtocol(uint32 feeProtocol0Old, uint32 feeProtocol1Old, uint32 feeProtocol0New, uint32 feeProtocol1New)
    - event: SetLmPoolEvent(address addr)
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint128 protocolFeesToken0, uint128 protocolFeesToken1)
unordered_multichain_mode: true
preload_handlers: true
